# Generated by Django 6.0.5 on 2026-05-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='value_choices',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('н', 'н'), ('нб', 'нб')], max_length=10, null=True),
        ),
    ]
