# Generated by Django 6.0.5 on 2026-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_attendance_grade_alter_grade_value_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='address_school_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='address_school_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='name_school_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='name_school_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
